[toolchain]
anchor_version = "1.1.2"

[features]
resolution = true
skip-lint = false

[programs.localnet]
warden = "6nX7pb3j5NTebXnP3dqCcxniRe7fJqwvfNi461g4Dm2"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "echo 'Phase 1 adds anchor tests'"
